name: Test Grammar

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Tree-sitter CLI
        uses: tree-sitter/setup-action@v2
        with:
          install-lib: false

      - run: tree-sitter generate
      - run: tree-sitter test

  compile:
    name: Compile and Upload Artifacts
    runs-on: ubuntu-latest
    needs:
      test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Tree-sitter CLI
        uses: tree-sitter/setup-action@v2
        with:
          install-lib: false

      - run: tree-sitter generate
      - run: tree-sitter build -o ./tree-sitter-autohotkey.dll

      - uses: actions/upload-artifact@v4
        with:
          name: Compiled Binary & Build Artifacts
          path: |
            ./tree-sitter-autohotkey.dll
            ./src/